### ISSUE TITLE
Dependency missing?

### ISSUE THREAD

**Issue by anseljh** [commonform/commonform-fix-strings#3]
My `package.json` includes:

```
  "dependencies": {
    "commonform-fix-strings": "^2.0.0",
    "commonform-validate": "^1.0.1",
    "eslint": "^5.16.0"
  },
```

Here's what I'm importing in a script:

```
var fs = require('fs')
var assert = require('assert')
var validate = require('commonform-validate')
var fixStrings = require('commonform-fix-strings')
```

I commented out everything else, so all that's left is those imports. After a fresh `npm install`, here's the output I get:

```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module './replacements'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/anseljh/Code/amender-experiments/node_modules/commonform-fix-strings/replace-unicode.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

`npm` is 6.9.0, `node` is 10.15.3.

**Comment by kemitchell** [comment]
Typo. Fixed in v5.0.2.
